### ISSUE TITLE
sleep: cannot read realtime clock: Operation not permitted

### ISSUE THREAD

**Issue by NimrodelGR** [mikenye/gitbook-adsb-guide#40]
Hello again,

after months of uninterrupted operation I am getting this error since 10 hours ago:

readsb        | sleep: cannot read realtime clock: Operation not permitted

No changes have been made to the system up to that point.

Tried updating docker, docker-compose and upgrading containers with no luck.

Any thoughts?

**Comment by kimfr** [comment]
I had the same issue on a RPi 3B+ - this is due to running Buster 32-bit. Most of the containers are built using Bullseye nowadays.

There is several solution as per https://github.com/sdr-enthusiasts/Buster-Docker-Fixes
I opted for Option 1 - ie. downloaded script from above link and updated libseccomp2 - at least until I re-image the RPi with Bullseye.

**Comment by NimrodelGR** [comment]
Thank you very much @kimfr for the suggestion!

I followed Option 1 which completed successfully but the problem remains (after restarting containers).

I wonder if the other system updates or container upgrades I tried broke something.

`docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
`

**Comment by NimrodelGR** [comment]
Problem solved after restarting containers once again
